# -*- coding: utf-8 -*-
"""Noticias.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/14ZP3LrjPqd6UPlKVn8sxj3Gc9CbQr8-x
"""

import requests
import bs4

url = "https://www.minuto30.com/"

response = requests.get(url)

soup = bs4.BeautifulSoup(response.text, 'html.parser')
news = soup.select('.medellinhome a')

noticias = []
links=[]

for item in news:

    if item.text == "":
      noticias.append("Sin Titulo")
    else:
      noticias.append(item.text)
      
    links.append(item.get("href"))

dictNoticias = {}
dictNoticias['Noticias']= noticias
dictNoticias['links']= links

import pandas as pd 
noticiasMin30 = pd.DataFrame(dictNoticias)
noticiasMin30

noticiasMin30.to_csv('noticiasMin30.csv', index=False)